### ISSUE TITLE
error while installing paypal fe

### ISSUE THREAD

**Issue by rudracomputech** [scandipwa/paypal-fe#2]
npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'paypal@1.0.1',
npm WARN EBADENGINE   required: { node: '0.8.x', npm: '1.1.x' },
npm WARN EBADENGINE   current: { node: 'v14.17.6', npm: '8.0.0' }
npm WARN EBADENGINE }

my package.json

<pre>
{
    "name": "my-first-app",
    "version": "0.0.1",
    "license": "OSL-3.0",
    "dependencies": {
        "@scandipwa/scandipwa": "5.2.2",
        "@scandipwa/scandipwa-scripts": "2.4.19",
        "@scandipwa/eslint-config": "0.1.36",
        "@tilework/mosaic": "0.1.4",
        "@tilework/mosaic-craco": "0.0.5",
        "@scandipwa/stripe-payments": "file:packages/stripe-payments",
        "@scandipwa/paypal": "file:packages/paypal"
    },
    "scandipwa": {
        "type": "theme",
        "locales": {
            "en_US": true
        },
        "parentTheme": "@scandipwa/scandipwa",
        "extensions": {
			"stripe-payments":true,
			"paypal":true
		}
    },
    "scripts": {
		"start": "scandipwa-scripts start",
		"build": "scandipwa-scripts build",
		"postinstall": "scandipwa-scripts link",
		"postupdate": "scandipwa-scripts link"
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "eslintConfig": {
        "extends": "@scandipwa"
    },
    "proxy": "https://m2.babybeddingdesign.com/"
}
</pre>

**Please help**

**Comment by rudracomputech** [comment]
Below is the full error code list any suggestion please thankyou in advance

<pre>
BUILD_MODE=magento npm run build

> my-first-app@0.0.1 build
> scandipwa-scripts build

Error: Cannot find module 'paypal/package.json'
Require stack:
- /var/www/websites/my.localdomain.com/my-first-app/node_modules/@tilework/mosaic-dev-utils/package-path.js
- /var/www/websites/my.localdomain.com/my-first-app/node_modules/@tilework/mosaic-dev-utils/parent-theme.js
- /var/www/websites/my.localdomain.com/my-first-app/node_modules/@scandipwa/next-emulator/lib/pages/defined-pages.js
- /var/www/websites/my.localdomain.com/my-first-app/node_modules/@scandipwa/next-emulator/lib/generate-pages.js
- /var/www/websites/my.localdomain.com/my-first-app/node_modules/@scandipwa/scandipwa-scripts/bin/scandipwa-scripts.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at getPackagePath (/var/www/websites/my.localdomain.com/my-first-app/node_modules/@tilework/mosaic-dev-utils/package-path.js:19:17)
    at /var/www/websites/my.localdomain.com/my-first-app/node_modules/@tilework/mosaic-dev-utils/extensions-core.js:57:29
    at Array.reduce (<anonymous>)
    at /var/www/websites/my.localdomain.com/my-first-app/node_modules/@tilework/mosaic-dev-utils/extensions-core.js:55:88
    at memoized (/var/www/websites/my.localdomain.com/my-first-app/node_modules/memoizee/lib/configure-map.js:81:23)
    at Object.<anonymous> (/var/www/websites/my.localdomain.com/my-first-app/node_modules/@tilework/mosaic-dev-utils/extensions.js:16:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/websites/my.localdomain.com/my-first-app/node_modules/@tilework/mosaic-dev-utils/package-path.js',
    '/var/www/websites/my.localdomain.com/my-first-app/node_modules/@tilework/mosaic-dev-utils/parent-theme.js',
    '/var/www/websites/my.localdomain.com/my-first-app/node_modules/@scandipwa/next-emulator/lib/pages/defined-pages.js',
    '/var/www/websites/my.localdomain.com/my-first-app/node_modules/@scandipwa/next-emulator/lib/generate-pages.js',
    '/var/www/websites/my.localdomain.com/my-first-app/node_modules/@scandipwa/scandipwa-scripts/bin/scandipwa-scripts.js'
  ]
}


ERROR!

     Loading of plugin paypal failed.
     Try installing it using npm i paypal command.
     Otherwise, disable the extension in the root package.json file:
     Append "paypal": false line to the end of the mosaic.extensions field.
